name: multiply-da-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - python =3.6*
  #
  # runtime dependencies
  #
  - beautifulsoup4 = 4.6.0
  - shapely = 1.6.2
  - gdal = 2.2.2
  - html5lib = 1.0.1
  - pyyaml = 3.12
  - requests = 2.18.4
  - pytest =3.8.0
